
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: pv-grafana
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    volumeHandle: "alx-deployaksalxstoragealxfileshare"  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      resourceGroup: MC_Alx-Deploy_alx-aks_eastus  # optional, only set this when storage account is not in the same resource group as node
      shareName: alxfileshare
    nodeStageSecretRef:
      name: azure-secret
      namespace: monitoring
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl  # disable sending byte range lock requests to the server and for applications which have challenges with posix locks
---   
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grafana
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: pv-grafana
  resources:
    requests:
      storage: 5Gi
